name: Monitoreo Aduana

on:
  schedule:
    # Lunes a Viernes: cada 30 min desde las 08:00 hasta las 20:30 hora Bolivia (12:00 UTC a 00:30 UTC)
    - cron: '0,30 12-23,0 * * 1-5'
    # Sábado: solo 2 veces (a las 12:00 y a las 16:00 hora Bolivia -> 16:00 y 20:00 UTC)
    - cron: '0 16,20 * * 6'
  workflow_dispatch:

jobs:
  escanear:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerías
        run: pip install -r requirements.txt

      - name: Instalar navegador Playwright
        run: playwright install --with-deps chromium

      - name: Ejecutar bot
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GSPREAD_CREDENTIALS_JSON: ${{ secrets.GSPREAD_CREDENTIALS_JSON }}
        run: python bot_aduana.py
